name: 'Export Terraform'
description: 'Exports standard Terraform environment variables for use by subsequent steps in the workflow'
inputs:
  tf_variables:
    description: ''
    required: true
    default: '{}'
runs:
  using: 'node20'
  main: 'index.js'
